# Generated by Django 5.0.6 on 2024-06-10 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Discount"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
            },
        ),
        migrations.CreateModel(
            name="Taille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taille",
                    models.CharField(blank=True, max_length=10, verbose_name="Size"),
                ),
            ],
            options={
                "verbose_name": "Size",
                "verbose_name_plural": "Sizes",
                "ordering": ["taille"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Quantity")),
                ("ordered", models.BooleanField(default=False, verbose_name="Ordered")),
                (
                    "ordered_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ordered Date"
                    ),
                ),
                ("subtotal", models.FloatField(default=0.0, verbose_name="Subtotal")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=128, verbose_name="Slug"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="store.categorie",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered", models.BooleanField(default=False, verbose_name="Ordered")),
                (
                    "ordered_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ordered Date"
                    ),
                ),
                ("totaux", models.FloatField(default=0.0, verbose_name="Total")),
                (
                    "all_quantity",
                    models.IntegerField(default=0, verbose_name="Total Quantity"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(to="store.cartitem", verbose_name="Orders"),
                ),
                (
                    "coupons",
                    models.ManyToManyField(
                        blank=True, to="store.coupons", verbose_name="Coupons"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=128, null=True, verbose_name="Slug"
                    ),
                ),
                ("price", models.FloatField(default=0.0, verbose_name="Price")),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Short Description"),
                ),
                (
                    "long_description",
                    models.TextField(blank=True, verbose_name="Long Description"),
                ),
                ("matiere", models.CharField(max_length=128, verbose_name="Material")),
                ("couleur", models.CharField(max_length=128, verbose_name="Color")),
                (
                    "thumbnails1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products",
                        verbose_name="Thumbnail 1",
                    ),
                ),
                (
                    "thumbnails2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products",
                        verbose_name="Thumbnail 2",
                    ),
                ),
                (
                    "thumbnails3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products",
                        verbose_name="Thumbnail 3",
                    ),
                ),
                (
                    "thumbnails4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products",
                        verbose_name="Thumbnail 4",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Updated At"
                    ),
                ),
                ("promo", models.BooleanField(default=False, verbose_name="Promo")),
                (
                    "percent_promo",
                    models.IntegerField(default=0, verbose_name="Promo Percentage"),
                ),
                (
                    "price_promo",
                    models.FloatField(default=0.0, verbose_name="Promo Price"),
                ),
                (
                    "product_stripe_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Stripe ID"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="store.categorie",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="Product",
            ),
        ),
        migrations.CreateModel(
            name="ProductTaille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Stock")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "taille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.taille",
                        verbose_name="Size",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Size",
                "verbose_name_plural": "Product Sizes",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tailles",
            field=models.ManyToManyField(
                related_name="products",
                through="store.ProductTaille",
                to="store.taille",
                verbose_name="Sizes",
            ),
        ),
    ]
