# Generated by Django 5.0.6 on 2024-06-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boutique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Store Name")),
                (
                    "ville",
                    models.CharField(max_length=100, null=True, verbose_name="City"),
                ),
                (
                    "zipcode",
                    models.CharField(max_length=10, null=True, verbose_name="Zipcode"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                (
                    "opening_hours",
                    models.CharField(max_length=255, verbose_name="Opening Hours"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "thumbnails_ville",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop",
                        verbose_name="City Thumbnail",
                    ),
                ),
                (
                    "shop_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop",
                        verbose_name="Shop Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
            },
        ),
    ]
