"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


import os

from pathlib import Path
import environ
# import dj_database_url
# Customisation des messages flash
from django.contrib.messages import constants as messages

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


environ.Env.read_env(BASE_DIR/".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY=env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'projet-stage-online.onrender.com']


X_FRAME_OPTIONS = 'SAMEORIGIN'

# Why ?
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True

ROOT_URLCONF = "shop.urls"
WSGI_APPLICATION = "shop.wsgi.application"

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_filters',
    "django.contrib.admin",
    "django.contrib.sites",
    "django.contrib.redirects",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_recaptcha',
    "store",
    "accounts",
    "map", 
    "mail",
]
SITE_ID = 1
 
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "shop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n", 
            ],
        },
    },
]

WSGI_APPLICATION = "shop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     "default": dj_database_url.parse(env('DATABASE_URL'))
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# fichier de destinationd des traductions
# a la racine du projet
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


# langue par défaut
LANGUAGE_CODE = "en-us"

# langues disponibles
LANGUAGES = [
    ('en', 'English'),
    ('fr', 'French'),
    ('es', 'Spanish'),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


AUTH_USER_MODEL = 'accounts.Customer'

EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
STRIPE_API_KEY = env("STRIPE_API_KEY")
END_POINT_WEBHOOK = env("END_POINT_WEBHOOK")
RECAPTCHA_PUBLIC_KEY = env("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = env("RECAPTCHA_PRIVATE_KEY")



MESSAGE_TAGS = {
    messages.DEBUG: 'bg-blue-100 border border-blue-400 text-blue-700',
    messages.INFO: 'bg-blue-100 border border-blue-400 text-blue-700',
    messages.SUCCESS: 'bg-green-100 border border-green-400 text-green-700',
    messages.WARNING: 'bg-yellow-100 border border-yellow-400 text-yellow-700',
    messages.ERROR: 'bg-red-100 border border-red-400 text-red-700',
}

RECAPTCHA_ERROR_MSG = {
    'required': 'Veuillez compléter le reCAPTCHA pour continuer.',
    'invalid': 'Le reCAPTCHA est invalide. Veuillez réessayer.',
    'timeout': 'Le reCAPTCHA a expiré. Veuillez rafraîchir la page et réessayer.',
    'connection_error': 'Une erreur de connexion s\'est produite. Veuillez vérifier votre connexion Internet et réessayer.'
}




JAZZMIN_SETTINGS = {
    'site_header': "YOURBRAND",
    'site_brand': "YOURBRAND",
    'site_logo': "images/logo.png",
    'welcome_sign': 'Bienvenue sur l\'espace Admin',
    'copyright': "Sooradje MAUVE",
    'top-menu_links': [
        {'name': 'Dashboard', 'url': 'admin:index', 'permissions': ['auth.view_user']},
        {'name': 'Produits', 'url': 'admin:store_product_changelist', 'permissions': ['auth.view_user']},
        {'name': 'Catégories', 'url': 'admin:store_categorie_changelist', 'permissions': ['auth.view_user']},
        {'name': 'Couleurs', 'url': 'admin:store_color_changelist', 'permissions': ['auth.view_user']},
        {'name': 'Stockage', 'url': 'admin:store_stockage_changelist', 'permissions': ['auth.view_user']},
        {'name': 'Commandes', 'url': 'admin:store_order_changelist', 'permissions': ['auth.view_user']},
        {'name': 'Paniers', 'url': 'admin:store_cart_changelist', 'permissions': ['auth.view_user']},
        {'name': 'Coupons', 'url': 'admin:store_coupons_changelist', 'permissions': ['auth.view_user']},
        {'name': 'Clients', 'url': 'admin:accounts_shopper_changelist', 'permissions': ['auth.view_user']},
        {'name': 'Boutiques', 'url': 'admin:map_boutique_changelist', 'permissions': ['auth.view_user']},
    ],
    "custom_links": {
        "Categorie": [{
            "name": "Catégories",
            "url": "admin:store_categorie_changelist",
            "icon": "fas fa-list",
        }],
        "Product": [{
            "name": "Produits",
            "url": "admin:store_product_changelist",
            "icon": "fa fa-plus-square",
        }],
        "ProductTaille": [{
            "name" : "Taille du produit",
            "url": "admin:store_producttaille_changelist",
            "icon": "fa fa-expand",
        }],
        "Taille": [{
            "name" : "Tailles disponibles",
            "url": "admin:store_color_changelist",
        }],
        "CartItem": [{
            "name" : "Commande",
            "url": "admin:store_cartitem_changelist",
        }],
        "Cart": [{
            "name" : "Panier",
            "url": "admin:store_cart_changelist",
        }],
        "Coupons": [{
            "name" : "Coupons de réduction",
            "url": "admin:store_coupons_changelist",
        }],
        "Customer": [{
            "name" : "Clients",
            "url": "admin:accounts_customer_changelist",
        }],
        "Boutiques": [{
            "name" : "Boutiques",
            "url": "admin:map_boutique_changelist",
        }],
    },
    "icons": {
        "store.Categorie": "fas fa-list",
        "store.Product": "fa fa-plus-square",
        "store.ProductTaille" :'fa fa-expand',
        "store.Taille": "fa fa-database",
        "store.Cart": "fa fa-shopping-bag",
        "store.CartItem": "fa fa-cart-plus",
        "store.Coupons": "fa fa-barcode",
        "accounts.Customer": "fa fa-user",
        "map.Boutique": "fa fa-home",
        
    },
    "related_modal_active": True,
    'order_with_respect_to': ['Customer','Categorie', 'Product', 'ProductTaille', 'Taille', 'Cart', 'Order', 'Coupons', 'Boutiques'],
    'theme': "darkly",

    # Paramètres personnalisés de la barre latérale
    'use_google_fonts_cdn': True,
    
    
    'custom_css': 'css/custom_admin.css',
    'custom_js': 'js/custom_admin.js',

    'ui_tweaks': {
        'theme': 'united',  
        'sidebar_bg': 'bg-red-500',
        'sidebar_top_bg': 'bg-yellow-500',
        'sidebar_bottom_bg': 'Purple',
        'sidebar_text': 'text-white',
        'sidebar_nav_active_bg': 'bg-Green-700', 
        'sidebar_nav_active_text': 'text-white',
    },
    
}

