# Generated by Django 5.0.6 on 2024-07-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_emails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='user',
        ),
    ]
